
-- Включаем расширение для функции gen_random_uuid
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Создание таблицы пользователей
CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);



CREATE TABLE IF NOT EXISTS body_parts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_name VARCHAR(50) UNIQUE NOT NULL
);



CREATE TABLE IF NOT EXISTS exercises (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    difficulty VARCHAR(20) NOT NULL DEFAULT 'Лёгкий' CHECK (difficulty IN ('Лёгкий', 'Средний', 'Сложный')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);



CREATE TABLE IF NOT EXISTS exercise_body_parts (
    exercise_id INT NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
    body_part_id INT NOT NULL REFERENCES body_parts(id) ON DELETE CASCADE,
    PRIMARY KEY (exercise_id, body_part_id)
);



-- Таблица шаблонов тренировок
CREATE TABLE IF NOT EXISTS training (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_name VARCHAR(100) NOT NULL,
    description TEXT,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);



-- Связь тренировки с упражнениями + опциональные «дефолтные» параметры
CREATE TABLE IF NOT EXISTS training_exercises (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_id INT NOT NULL REFERENCES training(id) ON DELETE CASCADE,
    exercise_id INT NOT NULL REFERENCES exercises(id),
    order_index INT NOT NULL DEFAULT 1,
    default_sets INT,
    default_reps INT,
    default_weight INT,
    UNIQUE (training_id, exercise_id, order_index)
);



-- Конкретная выполненная (или запланированная) тренировка пользователя
CREATE TABLE IF NOT EXISTS activity (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    training_id INT NOT NULL REFERENCES training(id) ON DELETE CASCADE,
    activity_name VARCHAR(100) NOT NULL,
    description TEXT,
    activity_type VARCHAR(20) NOT NULL,
    activity_difficult VARCHAR(20) NOT NULL,
    performed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);



-- Упражнения в рамках конкретной активности
CREATE TABLE IF NOT EXISTS activity_exercises (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id INT NOT NULL REFERENCES activity(id) ON DELETE CASCADE,
    exercise_id INT NOT NULL REFERENCES exercises(id),
    order_index INT NOT NULL DEFAULT 1,
    UNIQUE (activity_id, exercise_id, order_index)
);



-- Подходы по каждому упражнению в активности
CREATE TABLE IF NOT EXISTS activity_sets (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_exercise_id INT NOT NULL REFERENCES activity_exercises(id) ON DELETE CASCADE,
    set_number INT NOT NULL,
    reps INT NOT NULL,
    weight INT NOT NULL,
    UNIQUE (activity_exercise_id, set_number)
);



-- Питание пользователя за конкретный день (агрегированные БЖУ и калории)
CREATE TABLE IF NOT EXISTS nutrition (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(50) NOT NULL,
    description TEXT,
    calories INT NOT NULL,
    protein INT NOT NULL,
    fat INT NOT NULL,
    carb INT NOT NULL,
    day_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);



-- Цели пользователя
CREATE TABLE IF NOT EXISTS goal (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(50) NOT NULL,
    description TEXT,
    status INT DEFAULT NULL,
    achieve_at TIMESTAMP WITH TIME ZONE NULL,
    priority VARCHAR(20) NOT NULL CHECK (priority IN ('Низкий', 'Средний', 'Высокий')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);



-- Создание индексов для быстрого поиска
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at);
CREATE INDEX IF NOT EXISTS idx_users_last_seen_at ON users(last_seen_at);

CREATE INDEX IF NOT EXISTS idx_training_user_id ON training(user_id);
CREATE INDEX IF NOT EXISTS idx_training_exercises_training_id ON training_exercises(training_id);
CREATE INDEX IF NOT EXISTS idx_activity_user_id ON activity(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_training_id ON activity(training_id);
CREATE INDEX IF NOT EXISTS idx_nutrition_user_day_date ON nutrition(user_id, day_date);
CREATE INDEX IF NOT EXISTS idx_goal_user_id ON goal(user_id);

-- Создание таблицы для хранения токенов (для будущей аутентификации)
CREATE TABLE IF NOT EXISTS user_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token VARCHAR(500) NOT NULL,
    type VARCHAR(20) DEFAULT 'access' CHECK (type IN ('access', 'refresh')),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Создание индекса для токенов
CREATE INDEX IF NOT EXISTS idx_user_tokens_user_id ON user_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_user_tokens_token ON user_tokens(token);
CREATE INDEX IF NOT EXISTS idx_user_tokens_expires_at ON user_tokens(expires_at);

-- Функция для автоматического обновления updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
RETURN NEW;
END;
$$ language 'plpgsql';

-- Триггеры для автоматического обновления updated_at
DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_training_updated_at ON training;
CREATE TRIGGER update_training_updated_at BEFORE UPDATE ON training
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_activity_updated_at ON activity;
CREATE TRIGGER update_activity_updated_at BEFORE UPDATE ON activity
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_nutrition_updated_at ON nutrition;
CREATE TRIGGER update_nutrition_updated_at BEFORE UPDATE ON nutrition
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_goal_updated_at ON goal;
CREATE TRIGGER update_goal_updated_at BEFORE UPDATE ON goal
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
